application: tohobbs-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "1d"

handlers:
- url: /static
  static_dir: static

- url: /s/.*
  script: sysadmin.app
  login: admin

- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
